### ISSUE TITLE
Says Forbidden on Chrome

### ISSUE THREAD

**Issue by conc1erge** [BEEmod/BEEMOD#1]
Is this normal or What?
![image](https://user-images.githubusercontent.com/29669519/27780377-271d324a-5ffb-11e7-9aa9-2fa9966f6a87.png)

**Comment by TeamSpen210** [comment]
Try doing it again, or using a different browser.

**Comment by vrad-exe** [comment]
This repository exists?

**Comment by TeamSpen210** [comment]
It's really an archive if anything.

**Comment by conc1erge** [comment]
Hey, thanks, using Edge fixed it!
